### PR TITLE
options.url allows function

### PR DESCRIPTION
**Pull request by gpedro**
Closes #102

### CODE REVIEW

**Comment by gpedro** [comment]
ping @truckingsim

**Comment by gpedro** [comment]
@truckingsim done!

**Comment by truckingsim** [comment]
Thanks,

The computer I can build this on is at work, so I'll merge tomorrow some time.  Thanks for the timely response.

**Comment by gpedro** [comment]
ok! thanks <3

**Comment by gpedro** [comment]
@truckingsim forgive me for being annoying, can you merge and release?  <3

**Comment by gpedro** [comment]
<3 <3 <3

**Pull request merged**
