### PR TITLE
ajax-bootstrap-select.it-IT.js

### PR DESCRIPTION
**Pull request by masterix21**
Hi guys,

this is the italian translation of your plugin.

Thanks for the great job!

Happy sharing :)

### CODE REVIEW

**Comment by truckingsim** [comment]
@masterix21 can you move this file to: `Ajax-Bootstrap-Select/src/js/ajaxSelectPicker.locale/` instead of the dist folder?

The dist files are generated by a build script.

**Comment by truckingsim** [comment]
@masterix21 ok so now that's in the right place the build is failing because jshint fails on line `81`.  In our other language files we don't wrap them in

```js
!(function($){ 
    // ...
})(jQuery);
```

Can you remove lines 1-17 (these lines are generated by the build script), also can you remove line 18 and line 81 so that they work like the other language files. See the [ES Version](https://github.com/truckingsim/Ajax-Bootstrap-Select/blob/master/src/js/ajaxSelectPicker.locale/es-ES.js) for an example of what I'm looking for.

**Comment by markcarver** [comment]
@plach79, if/when you have a moment, could you verify this

**Comment by masterix21** [comment]
updated :)

**Comment by markcarver** [comment]
👍

**Pull request merged**
