### PR TITLE
android keyboard fix

### PR DESCRIPTION
**Pull request by Leoz83**

### CODE REVIEW

**Comment by truckingsim** [comment]
@Leoz83 can you do this fix in `src/js/ajaxSelectPicker.defaults.js`.  `dist/` files are generated by a build script and your change will be overwritten as is.

**Comment by truckingsim** [comment]
@markcarver keyCode `229` fires on a dead key keydown.  A dead key would be like the `´` above the e in déjà-vu. See [this stackoverflow post](https://stackoverflow.com/questions/25043934/is-it-ok-to-ignore-keydown-events-with-keycode-229) for more info.

I think knowing that it should be ok to do this change.

**Comment by markcarver** [comment]
@truckingsim, I honestly cannot remember for the life of me why I had put this in. There was a reason. However, after doing a bit of research and lack of git blaming to try and figure out why, I say it's fine to go ahead and remove.

FWIW, as a temporary measure users can override this default option with their own to remove it.

**Comment by truckingsim** [comment]
@markcarver I'm pretty sure I added it when I first wrote this when it was a single file and you just copied it over.  I think I got it from bootstrap-select when I first made this (I know I added the idea of ignored keys because of something in bootstrap-select).

**Comment by markcarver** [comment]
Heh you're right 😄 

https://github.com/truckingsim/Ajax-Bootstrap-Select/blob/v1.1.0/ajaxSelectPicker.js#L25

**Comment by Leoz83** [comment]
Sorry for the confusion :sweat_smile:

**Comment by markcarver** [comment]
@truckingsim, could you enable https://help.github.com/articles/configuring-pull-request-merge-squashing/

I'd like to squash merge these commits.

**Comment by truckingsim** [comment]
@markcarver it should be enabled already. I'm getting the option for it when I click merge, are you not?

**Comment by markcarver** [comment]
@truckingsim, no... must be my level of permissions or something. That's fine, PR looks good to me. Go ahead.

**Pull request merged**
