### PR TITLE
Allow the url option to be dynamically generated.

### PR DESCRIPTION
**Pull request by boneyao**

### CODE REVIEW

**Comment by truckingsim** [comment]
This LGTM I'll need to test it to make sure but I don't see anything wrong, will try to find the time to merge soon.

**Comment by markcarver** [comment]
Please only include changes to the source code in the PR. Including the compiled output makes reviewing difficult and can lead to stale/unmergeable PRs.

Also, it this feature needs to be documented in the options.

**Comment by markcarver** [comment]
This no longer merges. Please take out the compiled/distributed file changes.

**Comment by truckingsim** [comment]
Closing in favor of #102

**Pull request closed without merging**
