### PR TITLE
Fix selected text format

### PR DESCRIPTION
**Pull request by bercut497**
## Description (required)

if select element does not have title attribute
selectedTextFormat option will never be restored.
## Issues

fix issue  #22

### CODE REVIEW

**Comment by truckingsim** [comment]
Please don't commit compiled files.  Can you resubmit this without the compiled files?

**Comment by bercut497** [comment]
done

**Comment by truckingsim** [comment]
@bercut497 so I added a select that does what you posted as an issue in #112 that commit is: 7f28ef0.

You can run that example by pulling the latest master, `cd` into the example directory, run `npm install` and then `npm start`.  That html will be served at `localhost:8080`.  
It will be the last select on the page titled `Add option after init Ajax-Bootstrap-Select`.

I ran your code on that example and it doesn't seem to fix it.  I'm still seeing `emptyTitle` even though its setup like you example in #112.  Any idea why? Based off of what you said, this PR should fix it, but not seeing it fixed.

**Comment by bercut497** [comment]
my bad. 
i test not all. 
it happen when flag preserveSelected is true and option add after init
search string === '' and cache[''] === []
may be it can help : try to update cache for queryString key on refresh. (get new option array from $element and put into cache ) need test. you can get some regression.

**Comment by bercut497** [comment]
i will amend this mistake in commit.

**Comment by truckingsim** [comment]
@bercut497 just updated the example script one more time to match the conditions correctly and this does indeed seem to fix the problem.

**Comment by truckingsim** [comment]
Did a quick change locally and then merged and squashed this locally.  It didn't get picked up by github, but it is merged.

**Comment by truckingsim** [comment]
@bercut497 merge commit: e5f075f5ce517f10fc15ea794a6951657ad7094e

**Pull request closed without merging**
